<a href="https://colab.research.google.com/github/shakeelrifathcse/Data_analysis_pract_using_python/blob/main/DA_LIBRARY_PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

There are a coupie of important benefits of using Numpy arrays instead of Python lists for
operating on numerical data:
• Ease of use: You can write small, concise and intutive mathematical expressions like ( kal
* weights) . sum( ) rather than using loops & custom functions like crop_yeild .

• Performance: Numpy operations and functions are implemented internally in C++, which
makes them much faster than using Python statements & loops which are interpreted at
runtime

Numpy provides hundreds of functions for peforming operations on arrays. Here are some
common functions:

Mathematics: np. sum , np.exp , np.round , arithemtic operators

• Array manipulation: np.res ape , np.stack , np.concatenate , np. split

Linear Algebra: np.matmul , np.dot , np.transpose , np.eigvals

Statistics: np.mean , np.median , np. std , np.max

In [ ]:
import numpy as np

A. Introduction to NumPy
NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large multi-dimensional arrays and matrices, and a collection of mathematical functions to operate on these arrays


Basics of NumPy Arrays

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[8,9,80]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 80]]


In [ ]:
print(arr.shape)

(3, 3)


In [ ]:
print(arr.dtype)
print(arr.ndim)

int64
2


Array Indexing and Slicing

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:4])
print(a[-2:])
print(a[2:8])


[1 2 3 4]
[ 9 10]
[3 4 5 6 7 8]


Array Operations

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,5,5])
arr3 = arr1 + arr2
print(arr3)
print(arr1 ** 2)
print(arr3 * 2)

[6 7 8]
[1 4 9]
[12 14 16]


Multi-Dimensional Arrays

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(matrix[0,1])

2


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print()
#...........................#
print(x[1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[4 5 6]


In [ ]:
print(x[0])

[1 2 3]


Array Manipulation

In [ ]:
a =np.array([1,2,3,4,5,6])
ra = a.reshape(3,2, order ="c")
print(ra)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
h = ra.flatten()
print(h)

[1 2 3 4 5 6]


Array Aggregation and descriptive analysis


In [ ]:
arr = np.array(range(13))
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.max(arr))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
78
6.0
6.0
3.7416573867739413
12


Broadcasting

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
print(arr1 + arr2)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


 Random Numbers

In [ ]:
random_arr = np.random.randint(1,100, size = (100, 2))
random_arr2 = np.random.rand(5,5)
print(random_arr2)
print(random_arr)

[[0.18962989 0.69257276 0.75462793 0.11059673 0.69767233]
 [0.40327291 0.79563409 0.71498027 0.80696263 0.81496291]
 [0.97524555 0.88971011 0.19164152 0.4693481  0.53304033]
 [0.68812901 0.50007357 0.23374895 0.51349581 0.65836014]
 [0.91355746 0.18432588 0.98591687 0.64098232 0.80769585]]
[[ 4 51]
 [ 9 94]
 [25 94]
 [61 86]
 [51  6]
 [16 47]
 [70  2]
 [81 18]
 [60 70]
 [ 9 84]
 [47 29]
 [89 37]
 [ 6 81]
 [14 35]
 [65  3]
 [46 24]
 [51 13]
 [90 25]
 [87 46]
 [93 25]
 [59 15]
 [35 58]
 [73 83]
 [68 71]
 [23  8]
 [22 33]
 [11 59]
 [18 61]
 [37 45]
 [57 90]
 [63 63]
 [87  3]
 [67 82]
 [75 20]
 [92 24]
 [76 48]
 [ 6 66]
 [82  5]
 [58 75]
 [50 26]
 [40 25]
 [80 82]
 [ 9 99]
 [22 26]
 [25 99]
 [12 74]
 [36 70]
 [77 26]
 [87 55]
 [18 13]
 [90 81]
 [89 28]
 [65 24]
 [ 4 63]
 [24 70]
 [ 2 65]
 [99 99]
 [62 23]
 [ 2 95]
 [95 70]
 [94 87]
 [87 60]
 [47 63]
 [97 10]
 [67 35]
 [29 61]
 [38 20]
 [97 16]
 [24 23]
 [31 42]
 [45 52]
 [72 51]
 [84 26]
 [53 72]
 [26 98]
 [67 52]
 [18 78]
 [37 65]
 [34  9

Saving and Loading

In [ ]:
np.save('my_array.npy', arr)  # Save array to file
loaded_arr = np.load('my_array.npy')  # Load array from file
print(loaded_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


# numpy for data analysis

In [ ]:
import numpy as np

# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Array of zeros and ones
zeros = np.zeros((3, 3))
ones = np.ones((2, 2))
print(arr1d)
print(arr2d)
print(zeros)
print(h)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3 4 5 6]


In [ ]:
# Indexing a 1D array
print(arr1d[0])   # Access first element

# Indexing a 2D array
print(arr2d[1, 2])  # Access element at 2nd row, 3rd column

# Slicing a 1D array
print(arr1d[1:4])   # Slice elements from index 1 to 3


1
6
[2 3 4]


In [ ]:
# Element-wise addition, subtraction, multiplication, and division
arr1d_2 = np.array([5, 6, 7, 8, 9])

# Add two arrays
result_add = arr1d + arr1d_2

# Multiply arrays
result_mul = arr1d * 2

# Broadcasting (works on arrays of different shapes)
result_broadcast = arr1d / 2  # Add 2 to each element

print(result_add)
print(result_mul)
print(result_broadcast)


[ 6  8 10 12 14]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
# Generating random data
data = np.random.randint(40, 100,size =(100,1))
print(data)

# Mean, standard deviation, and variance
mean = np.mean(data)
print()
std_dev = np.std(data)

variance = np.var(data)

# Percentiles
percentile_25 = np.percentile(data, 25)
median = np.median(data)

print(f"Mean: {mean}, Std Dev: {std_dev}, Variance: {variance}")
print(f"25th Percentile: {percentile_25}, Median: {median}")


[[74]
 [91]
 [84]
 [97]
 [77]
 [75]
 [47]
 [62]
 [41]
 [59]
 [83]
 [79]
 [45]
 [91]
 [55]
 [48]
 [41]
 [50]
 [71]
 [60]
 [92]
 [56]
 [85]
 [90]
 [70]
 [73]
 [89]
 [83]
 [64]
 [99]
 [98]
 [41]
 [62]
 [93]
 [82]
 [86]
 [83]
 [61]
 [55]
 [61]
 [86]
 [79]
 [66]
 [98]
 [99]
 [66]
 [84]
 [85]
 [77]
 [60]
 [47]
 [70]
 [98]
 [66]
 [67]
 [82]
 [98]
 [86]
 [42]
 [69]
 [87]
 [87]
 [68]
 [93]
 [85]
 [77]
 [56]
 [94]
 [86]
 [84]
 [40]
 [48]
 [65]
 [72]
 [68]
 [60]
 [66]
 [52]
 [75]
 [84]
 [46]
 [72]
 [71]
 [67]
 [90]
 [50]
 [93]
 [44]
 [56]
 [50]
 [80]
 [83]
 [68]
 [86]
 [42]
 [82]
 [61]
 [69]
 [98]
 [45]]

Mean: 71.78, Std Dev: 16.927244312055045, Variance: 286.5315999999999
25th Percentile: 60.0, Median: 72.0


In [ ]:
# Sorting an array
sorted_data = np.sort(data)
print(sorted_data)




[[74]
 [91]
 [84]
 [97]
 [77]
 [75]
 [47]
 [62]
 [41]
 [59]
 [83]
 [79]
 [45]
 [91]
 [55]
 [48]
 [41]
 [50]
 [71]
 [60]
 [92]
 [56]
 [85]
 [90]
 [70]
 [73]
 [89]
 [83]
 [64]
 [99]
 [98]
 [41]
 [62]
 [93]
 [82]
 [86]
 [83]
 [61]
 [55]
 [61]
 [86]
 [79]
 [66]
 [98]
 [99]
 [66]
 [84]
 [85]
 [77]
 [60]
 [47]
 [70]
 [98]
 [66]
 [67]
 [82]
 [98]
 [86]
 [42]
 [69]
 [87]
 [87]
 [68]
 [93]
 [85]
 [77]
 [56]
 [94]
 [86]
 [84]
 [40]
 [48]
 [65]
 [72]
 [68]
 [60]
 [66]
 [52]
 [75]
 [84]
 [46]
 [72]
 [71]
 [67]
 [90]
 [50]
 [93]
 [44]
 [56]
 [50]
 [80]
 [83]
 [68]
 [86]
 [42]
 [82]
 [61]
 [69]
 [98]
 [45]]


In [ ]:
# Sorting an array
sorted_data = np.sort(data)

# Finding the index of max and min values
max_index = np.argmax(data)
min_index = np.argmin(data)

# Count occurrences of values (e.g., how many times '5' appears)
unique_values, counts = np.unique(data, return_counts=True)

print(f"Max at index: {max_index}, Min at index: {min_index}")
print(f"Unique values: {unique_values}, Counts: {counts}")


Max at index: 29, Min at index: 70
Unique values: [40 41 42 44 45 46 47 48 50 52 55 56 59 60 61 62 64 65 66 67 68 69 70 71
 72 73 74 75 77 79 80 82 83 84 85 86 87 89 90 91 92 93 94 97 98 99], Counts: [1 3 2 1 2 1 2 2 3 1 2 3 1 3 3 2 1 1 4 2 3 2 2 2 2 1 1 2 3 2 1 3 4 4 3 5 2
 1 2 2 1 3 1 1 5 2]


In [ ]:
# Broadcasting example
arr_broadcast = np.array([1, 2, 3])
broadcast_result = arr_broadcast * np.array([5])

print(broadcast_result)


[ 5 10 15]


In [ ]:
# Saving arrays to files
np.save("data.npy", arr1d)

# Loading arrays from files
loaded_data = np.load("data.npy")

print(loaded_data)


[1 2 3 4 5]


# Pandas

In [ ]:
import pandas as pd

# Series
# A pandas Series is a one-dimensional array with labels.

# Examples
list_data = [1, 2, 3, 4, 5]
series = pd.Series(list_data)
print(series)

# Series with Dictionary:
dict_data = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(dict_data)
print(series)

# Series with Custom Indexes
enrollments = [100, 200, 300, 400, 500]
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
series = pd.Series(enrollments, index=months)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
Jan    100
Feb    200
Mar    300
Apr    400
May    500
dtype: int64


In [ ]:
# Accessing the series Data:

# Accessing by the Position or Index
print(series[0])  # 100
# Accessing by the Label
print(series['Jan'])  # 100
# Accessing as Slicing
print(series[1:3])  # Feb    200
                    # Mar    300
print(series['Feb':'Apr'])  # Feb    200
                            # Mar    300
# Accessing Multiple Elements
print(series[['Jan', 'Mar', 'May']])  # Jan    100
                                      # Mar    300
                                      # May    500

100
100
Feb    200
Mar    300
dtype: int64
Feb    200
Mar    300
Apr    400
dtype: int64
Jan    100
Mar    300
May    500
dtype: int64


<ipython-input-26-5a229c49b5ed>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0])  # 100


In [ ]:
# Series Operations:

series = pd.Series([1, 2, 3, 4, None])
print(series + 10) # Add 10 to each element
print(series - 10) # Subtract 10 from each element
print(series * 10) # Multiply each element by 10

0    11.0
1    12.0
2    13.0
3    14.0
4     NaN
dtype: float64
0   -9.0
1   -8.0
2   -7.0
3   -6.0
4    NaN
dtype: float64
0    10.0
1    20.0
2    30.0
3    40.0
4     NaN
dtype: float64


In [ ]:
# Attributes

print(series.size)  # 5
print(series.shape) # (5,)
print(series.dtype) # int64
print(series.index) # RangeIndex(start=0, stop=5, step=1)
print(series.values) # [1 2 3 4 5]
print(series.isnull()) # False
print(series.notnull()) # True

5
(5,)
float64
RangeIndex(start=0, stop=5, step=1)
[ 1.  2.  3.  4. nan]
0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool


In [ ]:


print(series.sum()) # 15
print(series.mean()) # 3.0
print(series.median()) # 3.0
print(series.count()) # 5

10.0
2.5
2.5
4


Homeworrk by nexturn

In [ ]:
sales_data = pd.Series([150, 200, 90, 120, 300],
    index=['Product A', 'Product B', 'Product C', 'Product D', 'Product E'],)

print(sales_data)


# Exercise 2: Total Sales for the Week
"""Considering we have a one week of sales data from monday to friday"""
total_sales = sales_data.sum()
print("Total Sales for the Week :",total_sales)

# Exercise 3: Average Sales for the Week
average = sales_data.mean()
print("Avg sales :",average)

# Exercise 4 : Highest and Lowest Selling Products
highest_selling = sales_data.idxmax()
lowest_selling = sales_data.idxmin()

print("Highest Selling Product:", highest_selling)
print("Lowest Selling Product:", lowest_selling)

#Checking the product with Low Sales
high_sales = sales_data[sales_data > 150]
print("Products with Sales above 150 units:\n", high_sales)

#Checking the product with Low Sales
low_sales = sales_data[sales_data < 100]
print("Products with Low Sales:\n", low_sales)

sales_data['Product F'] = 100
print("Updated Sales Data:\n", sales_data)
















Product A    150
Product B    200
Product C     90
Product D    120
Product E    300
dtype: int64
Total Sales for the Week : 860
Avg sales : 172.0
Highest Selling Product: Product E
Lowest Selling Product: Product C
Products with Sales above 150 units:
 Product B    200
Product E    300
dtype: int64
Products with Low Sales:
 Product C    90
dtype: int64
Updated Sales Data:
 Product A    150
Product B    200
Product C     90
Product D    120
Product E    300
Product F    100
dtype: int64


In [ ]:
import pandas as pd

# Creating a panda dataframe for Product Sales from a dictionary

data = {
    'Product': ['Product A', 'Product B', 'Product C', 'Product D'],
    'Price': [150, 200, 90, 120],
    'Units Sold': [100, 150, 50, 70]
}

df = pd.DataFrame(data)
print(df)

# Basic Operation on DataFrame:

# Viewing the Data

# Display the first 5 rows of the DataFrame
print("\nFirst 5 rows of the DataFrame:")
print(df.head())
# Display the first 2 rows of the DataFrame
print("\nFirst 2 rows of the DataFrame:")
print(df.head(2))

# Display the last 3 rows of the DataFrame
print("\nLast 3 rows of the DataFrame:")
print(df.tail(3))

# Shape of the DataFrame
print("\nShape of the DataFrame:", df.shape)

# Information about the DataFrame
print("\nInformation about the DataFrame:")
print(df.info())

# Display the columns of the DataFrame
print("\nColumns of the DataFrame:")
print(df.columns)

# Get the summary or statistics of the Data frame
print("\nSummary of the DataFrame:")
print(df.describe())

# **************************************** #

# Selecting Columns

print(df['Product'])
print(df[['Product', 'Price']])

# Selecting Rows

print(df.iloc[0])   # Selecting the first row
print(df.loc[0])    # Selecting the first row

# Selecting Multiple Rows
print(df.iloc[0:2]) # Selecting the first two rows

# Selecting Rows based on Condition
print(df[df['Price'] > 100])

# **************************************** #

# Adding or Removing the Data to/from DataFrame

# Adding a new column to the DataFrame
# df['Total_Sales'] = df['Price'] * df['Units Sold']
# print(df)

# Removing a column from the DataFrame
# df.drop('Total_Sales', axis=1, inplace=True)
# print(df)

# Adding a new row to the DataFrame
new_row = {'Product': 'Product E', 'Price': 250, 'Units Sold': 120}
another_row = {'Product': 'Product F', 'Price': 180, 'Units Sold': 90}
df = df._append(new_row, ignore_index=True)
df = df._append(another_row, ignore_index=True)
print(df)

# Adding a new column again..
df['Total_Sales'] = df['Price'] * df['Units Sold']
print(df)

# **************************************** #

# Filter Products with Total Sales above 10000
high_price_products = df[df['Total_Sales'] > 10000]
print("\nProducts with Total Sales above 10000:\n", high_price_products)

# Filter Products Priced Below Average Price
below_avg_price = df[df['Price'] < df['Price'].mean()]
print("\nProducts Priced Below Average Price:\n", below_avg_price)

# **************************************** #

# Grouping Data

# Adding a Category Column to Data Frame

df['Category'] = ['Electronics', 'Clothing', 'Electronics', 'Grocery', 'Electronics', 'Clothing']
print(df)

# Grouping Data by Category and Calculating the total sales for each category
grouped_data = df.groupby('Category')['Total_Sales'].sum()
print("\nGrouped Data by Category:")
print(grouped_data)

     Product  Price  Units Sold
0  Product A    150         100
1  Product B    200         150
2  Product C     90          50
3  Product D    120          70

First 5 rows of the DataFrame:
     Product  Price  Units Sold
0  Product A    150         100
1  Product B    200         150
2  Product C     90          50
3  Product D    120          70

First 2 rows of the DataFrame:
     Product  Price  Units Sold
0  Product A    150         100
1  Product B    200         150

Last 3 rows of the DataFrame:
     Product  Price  Units Sold
1  Product B    200         150
2  Product C     90          50
3  Product D    120          70

Shape of the DataFrame: (4, 3)

Information about the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Product     4 non-null      object
 1   Price       4 non-null      int64 
 2   Units Sold  4 non-null      in

In [ ]:
import pandas as pd

# Creating the dataset with updated quantities
data = {
    'Customer ID': [101, 102, 103, 104, 105],
    'Customer Name': ['Tom', 'Jerry', 'Mickey', 'Minnie', 'Donald'],
    'Product': ['Laptop', 'Smartphone', 'Tablet', 'Laptop', 'Smartphone'],
    'Price': [1200, 800, 400, 1200, 800],
    'Quantity': [1, 2, 2, 1, 3],
    'Purchase Date': pd.to_datetime(['2021-06-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05'])
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Printing the DataFrame and its shape
print(df)
print(df.shape)

# 1. Total Revenue
df['Total Price'] = df['Price'] * df['Quantity']
total_revenue = df['Total Price'].sum()
print(f"Total Revenue: {total_revenue}")

# 2. Customer with the Highest Purchase
highest_purchase_customer = df.loc[df['Total Price'].idxmax(), 'Customer Name']
print(f"Customer with the Highest Purchase: {highest_purchase_customer}")

# 3. Most Purchased Product
most_purchased_product = df['Product'].mode()[0]
print(f"Most Purchased Product: {most_purchased_product}")

# 4. Purchases in January per Customer
january_purchases = df[df['Purchase Date'].dt.month == 1]
print("January Purchases Per Customer:")
print(january_purchases[['Customer Name', 'Total Price']])


   Customer ID Customer Name     Product  Price  Quantity Purchase Date
0          101           Tom      Laptop   1200         1    2021-06-01
1          102         Jerry  Smartphone    800         2    2021-01-02
2          103        Mickey      Tablet    400         2    2021-01-03
3          104        Minnie      Laptop   1200         1    2021-01-04
4          105        Donald  Smartphone    800         3    2021-01-05
(5, 6)
Total Revenue: 7200
Customer with the Highest Purchase: Donald
Most Purchased Product: Laptop
January Purchases Per Customer:
  Customer Name  Total Price
1         Jerry         1600
2        Mickey          800
3        Minnie         1200
4        Donald         2400


# Linear Algebra Functions

Matrix Multiplication: Using np.dot() or @ to perform matrix multiplication.

Eigenvalues and Eigenvectors: Solving eigenvalue problems with np.linalg.eig().

Determinants: Calculate the determinant of a matrix using np.linalg.det().

Solving Linear Systems: Solve systems of linear equations with np.linalg.solve().

In [ ]:
import numpy as np

# Example matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.dot or @ operator
result_dot = np.dot(A, B)
result_at = A @ B
print("Matrix multiplication using np.dot:\n", result_dot)
print("Matrix multiplication using @ operator:\n", result_at)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

# Determinant of matrix A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Solving linear equations
# Example: Ax = b, where A is a matrix and b is a vector
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solution to the linear system Ax = b:", x)


Matrix multiplication using np.dot:
 [[19 22]
 [43 50]]
Matrix multiplication using @ operator:
 [[19 22]
 [43 50]]
Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Determinant of A: -2.0000000000000004
Solution to the linear system Ax = b: [0.  0.5]


# Final Case Study: NumPy for Data Analysis
Now, let's apply everything you've learned to solve a case study using NumPy for data analysis.

Case Study: Analyzing a Toy Sales Dataset
Problem: You are given a dataset of monthly toy sales for different regions. You need to:

Compute the total sales for each month.
Find the region with the highest sales in any given month.
Calculate the average monthly sales for each region.

In [ ]:
import numpy as np

# Toy sales data (rows: regions, columns: months)
sales_data = np.array([
    [200, 220, 250, 300, 310],  # Region 1
    [180, 210, 230, 280, 300],  # Region 2
    [150, 190, 220, 270, 290],  # Region 3
])

months = ["Jan", "Feb", "Mar", "Apr", "May"]
regions = ["Region 1", "Region 2", "Region 3"]


In [ ]:
# total sales of each month
# Calculate total sales for January (first column)
total_sales_january = np.sum(sales_data[:, 0])
print("Jan total sales:",total_sales_january)

total_sales_feb = np.sum(sales_data[:, 1])
print("feb total sales:",total_sales_feb)

Jan total sales: 530
feb total sales: 620


In [ ]:
region1 = np.sum(sales_data[0,:])
print("region 1 : ",region1)

region2 = np.sum(sales_data[1,:])
print("region 2: ",region2)

region3 = np.sum(sales_data[2,:])
print("region 3 : ",region3)

highest_sales_by_region = np.max([region1,region2,region3])
print(f"highest sales {highest_sales_by_region}")

region 1 :  1280
region 2:  1200
region 3 :  1120
highest sales 1280


In [ ]:
# Compute total sales for each month
total_sales_per_month = np.sum(sales_data, axis=0)

# Display the total sales for each month
for month, total in zip(months, total_sales_per_month):
    print(f"Total sales in {month}: {total}")


Total sales in Jan: 530
Total sales in Feb: 620
Total sales in Mar: 700
Total sales in Apr: 850
Total sales in May: 900


In [ ]:
highest_sales_by_region = np.sum(sales_data, axis = 1)
for region,total in zip(regions, highest_sales_by_region):
  print(f"{region}:{total}")


Region 1:1280
Region 2:1200
Region 3:1120


In [ ]:
highest_sales_by_region = np.mean(sales_data, axis = 1)
for region,total in zip(regions, highest_sales_by_region):
  print(f"{region}:{total}")

Region 1:256.0
Region 2:240.0
Region 3:224.0


In [ ]:
# Compute average monthly sales for each region
average_sales_per_region = np.mean(sales_data, axis=1)

# Display the average monthly sales for each region
for region, average in zip(regions, average_sales_per_region):
    print(f"Average monthly sales for {region}: {average:.2f}")


Average monthly sales for Region 1: 256.00
Average monthly sales for Region 2: 240.00
Average monthly sales for Region 3: 224.00


In [ ]:
# Find the region with the highest sales for each month
highest_sales_indices = np.argmax(sales_data, axis=0)

# Display the region with the highest sales for each month
for month, index in zip(months, highest_sales_indices):
    print(f"Highest sales in {month}: {regions[index]} with {sales_data[index][months.index(month)]} sales")


Highest sales in Jan: Region 1 with 200 sales
Highest sales in Feb: Region 1 with 220 sales
Highest sales in Mar: Region 1 with 250 sales
Highest sales in Apr: Region 1 with 300 sales
Highest sales in May: Region 1 with 310 sales


In [ ]:
# this why np array is usefull for numerical computation than python list

"""ERROR OCCUR"""

a = [40,50,44]
b= [0.2,3.4,5.5]
result = (a * b).sum()

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
a = np.array([40,50,44])
b= np.array([0.2,3.4,5.5])
result = (a * b).sum()
s = a @ b
print(s)

print(result)

In [ ]:
#3 d array
arr3 = np. array([[[1,2,3,],[2,3,4]],[[2,3,4],[4,5,6]]])
arr3.shape


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
# broadcasting

r = arr1 + arr2

print(r)

[[2 4 6]
 [5 7 9]]


In [ ]:
a1 = np.array([[1],[2],[3]])
s = a1 + arr1
#another type of broadcasting
print(s)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
(arr1 != arr2).sum()


3

In [ ]:
mul = np.array([[[1,2,3,4],[1,2,3,4]],[[5,6,7,8],[7,5,4,3]]])

In [ ]:
print(mul)
mul.shape
mul.ndim

[[[1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [7 5 4 3]]]


3

In [ ]:
 mul[:,1]


array([[1, 2, 3, 4],
       [7, 5, 4, 3]])

In [ ]:
 np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.rand(3)

array([0.87307063, 0.00210338, 0.34935787])

In [ ]:
np.full((3,3),42)

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [ ]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
np.arange(0,100,5).reshape(20,1)

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50],
       [55],
       [60],
       [65],
       [70],
       [75],
       [80],
       [85],
       [90],
       [95]])

In [ ]:
np.linspace(3,27,30)

array([ 3.        ,  3.82758621,  4.65517241,  5.48275862,  6.31034483,
        7.13793103,  7.96551724,  8.79310345,  9.62068966, 10.44827586,
       11.27586207, 12.10344828, 12.93103448, 13.75862069, 14.5862069 ,
       15.4137931 , 16.24137931, 17.06896552, 17.89655172, 18.72413793,
       19.55172414, 20.37931034, 21.20689655, 22.03448276, 22.86206897,
       23.68965517, 24.51724138, 25.34482759, 26.17241379, 27.        ])

In [ ]:
 arr1 = np.array([1,"a",2])

In [ ]:
print(np.array([[[
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.5]]]
    ]]).ndim)

5


In [ ]:
arr3 = np.array([
    [[11, 12, 8, 19],
     [13, 21, 4, 19]],

    [[5, 1, 7, 21],
     [13, 9, 6, 1]],

    [[9, 32, 18, -5],
     [15, 25, 11, -6]]])
print(arr3[:2, 1].sum())

86


In [ ]:
a = [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]]
b = [[1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]]

c = np.concatenate([a, b], axis=0)
w = np.concatenate([a, b], axis=1)

print(c)
print(w)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
h = np.hstack([a,b])
print(h)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
print(arr1,a1)

['1' 'a' '2'] [[1]
 [2]
 [3]]


In [ ]:
for i,x in zip(arr1,a1):
  print(i)
  print(x)

1
[1]
a
[2]
2
[3]


In [ ]:
from scipy import stats
arr = [1, 2, 2,2, 3, 4, 4, 4, 5]
mode_value = stats.mode(arr)
print(mode_value)


ModeResult(mode=2, count=3)
